import type { Metadata } from "next";
import "../globals.css";
import "./styles.css"

export const metadata: Metadata = {
  title: "Movies By Nihat",
  description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    );
}
