import type { Metadata } from "next";
import "../globals.css";
import Header from "@/widgets/Header";

export const metadata: Metadata = {
  title: "Movies By Nihat",
  description: "Generated by create next app",
};


export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <Header />
                <main>{children}</main>
            </body>
        </html>
    );
}
